# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    # VM 1 - Database
    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "ubuntu/focal64"
  
      vm1.vm.network "private_network", ip: "192.168.33.10"

      vm1.vm.network "forwarded_port", guest: 3306, host: 3306
    end
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end
      
end
    